### ISSUE TITLE
IO Polarity register support missing for MCP23017

### ISSUE THREAD

**Issue by shadowclaw** [adafruit/Adafruit_CircuitPython_MCP230xx#34]
It appears that only one of the IO Polarity registers is defined (IPOLA) and is only set during the class init for the MCP23017.  The register is labelled as IPOLA but is being used to address both IPOLA and IPOLB.  Would it be possible to added the second register (IPOLB = 0x03) and get/set support to the class for this?

**Comment by ladyada** [comment]
if you add it and perform a pull request, that would be the best way to get support for that register! please try it :)

**Comment by shadowclaw** [comment]
#35 Created the request but I am not sure what "black" is or why it is failing

**Comment by shadowclaw** [comment]
latest release (v2.4.2) has this included now.
