### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [adafruit/Adafruit_CircuitPython_MCP230xx#55]
Hi, In **Adafruit_CircuitPython_MCP230xx**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
Adafruit-Blinka
adafruit-circuitpython-busdevice
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **Adafruit-Blinka** can be changed to *>=0.1.5,<=8.0.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the Adafruit-Blinka</summary>
 <pre>micropython.const
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>str
print
super
adafruit_mcp230xx.mcp23017.MCP23017.clear_ints
os.environ.get
busio.I2C
digital_inout.DigitalInOut
self._write_u8
sphinx_rtd_theme.get_html_theme_path
sys.path.insert
adafruit_mcp230xx.mcp23s17.MCP23S17.get_pin
bus_device.write_readinto
RPi.GPIO.setmode
adafruit_mcp230xx.mcp23s17.MCP23S17
self._write_u16le
digitalio.DigitalInOut
RPi.GPIO.add_event_detect
RPi.GPIO.cleanup
bus_device.write_then_readinto
port_a_pins.append
port_b_pins.append
adafruit_mcp230xx.mcp23s17.MCP23S17.clear_ints
adafruit_mcp230xx.mcp23017.MCP23017
datetime.datetime.now
self._read_u16le
super.__init__
_enable_bit
micropython.const
self._read_u8
busio.SPI
format
adafruit_mcp230xx.mcp23017.MCP23017.get_pin
bytearray
ValueError
_clear_bit
os.path.abspath
RPi.GPIO.setup
adafruit_bus_device.i2c_device.I2CDevice
enumerate
pins.append
_get_bit
bus_device.write
range
adafruit_bus_device.spi_device.SPIDevice
time.sleep
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by tekktrik** [comment]
Hi, we're all set, but thank you for offering!
