### ISSUE TITLE
Where did you find the Registers?

### ISSUE THREAD

**Issue by Tim-Jackins** [adafruit/Adafruit_CircuitPython_MCP230xx#8]
In lines 43-78 of [adafruit_mcp230xx.py](https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/blob/master/adafruit_mcp230xx.py) you have `Registers and other constants`. Where did you find these? I'm trying to transform this library for use with the pcf8574, and I can't find anything that looks like these registers. The spec sheet for the chip I'm using is [here](https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf). Any insight would be much appreciated!

**Comment by tannewt** [comment]
Looks like they are from this datasheet: https://cdn-shop.adafruit.com/datasheets/mcp23017.pdf
