### ISSUE TITLE
Add support for hardware interrupts

### ISSUE THREAD

**Issue by Misiu** [adafruit/Adafruit_CircuitPython_MCP230xx#9]
Arduino library has support for interrupts - https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library/blob/master/examples/interrupt/interrupt.ino
Could You also add support for them in this library?
There is a PR for Home Assistant that is using Your awesome library, but having support for hardware interrupts would eliminate the need to pull for state changes.

This is already done in Arduino version so this is for sure doable.

**Comment by ladyada** [comment]
its here
https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/blob/master/examples/mcp230xx_leds_and_buttons_irq.py

**Comment by Misiu** [comment]
@ladyada that was fast.
thank You :)
